# Read the Docs configuration file for spe9-geomodeling
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, set of tools, and environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Python configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

# Optional but recommended, show the version of our package on RTD
# This requires the package to be installed
formats:
  - pdf
  - epub
